/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Trabalho5.telas;

import Trabalho5.bd.EdicaoBD;
import Trabalho5.bd.EventoBD;
import Trabalho5.bd.InscritoBD;
import Trabalho5.bd.PatrocinadorBD;
import Trabalho5.bd.PatrocinioBD;
import Trabalho5.bd.PessoaBD;
import java.sql.Date;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriela
 */
public class TelaPatrocinio extends javax.swing.JFrame {

    /**
     * Creates new form TelaPatrocinio
     */
    public TelaPatrocinio() {
        initComponents();
        loadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        patrocinioTPane = new javax.swing.JTabbedPane();
        patrocinioInserir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        insertByName = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        inserirEv_Patrocinador = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        inserirEd_Patrocinador = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inserirValor_Patrocinio = new javax.swing.JTextField();
        inserirButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        inserirData_Patrocinio = new org.jdesktop.swingx.JXDatePicker();
        patrocinioBuscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        buscarPatrocinio_Pat = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buscarPatrocinio_Valor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        buscarPatrocinio_Saldo = new javax.swing.JTextField();
        buscarPatrocinio_Button = new javax.swing.JButton();
        buscarPatrocinio_Evento = new javax.swing.JComboBox();
        buscarPatrocinio_Edicao = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        buscarPatrocinio_Data = new javax.swing.JTextField();
        buscarPatrocinio_CNPJ = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        patrocinioDeletar = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        deletarPatrocinio_Evento = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        deletarPatrocinio_CNPJ = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        deletarPatrocinio_Data = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        deletarPatrocinio_Valor = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        deletarPatrocinio_Saldo = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        deletarPatrocinio_Button = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        deletarPatrocinio_Edicao = new javax.swing.JComboBox();
        deletarPatrocinio_Pat = new javax.swing.JComboBox();
        editarPatrocinio_Valor = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        editarPatrocinio_Evento = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        editarPatrocinio_valor = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        editarPatrocinio_Button = new javax.swing.JButton();
        editarPatrocinio_Edicao = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        editarPatrocinio_Pat = new javax.swing.JComboBox();
        editarPatrocinio_Data = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Selecione e digite as informações desejadas no campo abaixo e clique em inserir");

        jLabel2.setText("Patrocinador:");

        insertByName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        insertByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertByNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Evento:");

        inserirEv_Patrocinador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        inserirEv_Patrocinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirEv_PatrocinadorActionPerformed(evt);
            }
        });

        jLabel4.setText("Edição:");

        inserirEd_Patrocinador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        inserirEd_Patrocinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirEd_PatrocinadorActionPerformed(evt);
            }
        });

        jLabel5.setText("Data do patrocínio:");

        jLabel6.setText("Valor do patrocínio:");

        inserirButton.setText("Inserir");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patrocinioInserirLayout = new javax.swing.GroupLayout(patrocinioInserir);
        patrocinioInserir.setLayout(patrocinioInserirLayout);
        patrocinioInserirLayout.setHorizontalGroup(
            patrocinioInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patrocinioInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patrocinioInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addGroup(patrocinioInserirLayout.createSequentialGroup()
                        .addGroup(patrocinioInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(patrocinioInserirLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(patrocinioInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(patrocinioInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inserirData_Patrocinio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inserirValor_Patrocinio)))
                            .addComponent(insertByName, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inserirEv_Patrocinador, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inserirEd_Patrocinador, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
            .addGroup(patrocinioInserirLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(inserirButton)
                .addGap(57, 57, 57)
                .addComponent(jButton2)
                .addGap(0, 0, 0))
        );
        patrocinioInserirLayout.setVerticalGroup(
            patrocinioInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patrocinioInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inserirEv_Patrocinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inserirEd_Patrocinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(patrocinioInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirValor_Patrocinio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(patrocinioInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inserirData_Patrocinio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(patrocinioInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirButton)
                    .addComponent(jButton2))
                .addGap(80, 80, 80))
        );

        patrocinioTPane.addTab("Inserir", patrocinioInserir);

        jLabel7.setText("Evento:");

        buscarPatrocinio_Pat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        buscarPatrocinio_Pat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPatrocinio_PatActionPerformed(evt);
            }
        });

        jLabel12.setText("Data do patrocínio:");

        jLabel13.setText("Valor do patrocínio:");

        jLabel14.setText("Saldo:");

        buscarPatrocinio_Button.setText("Voltar");
        buscarPatrocinio_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPatrocinio_ButtonActionPerformed(evt);
            }
        });

        buscarPatrocinio_Evento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        buscarPatrocinio_Evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPatrocinio_EventoActionPerformed(evt);
            }
        });

        buscarPatrocinio_Edicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        buscarPatrocinio_Edicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPatrocinio_EdicaoActionPerformed(evt);
            }
        });

        jLabel15.setText("Patrocinador:");

        jLabel16.setText("Edição:");

        buscarPatrocinio_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPatrocinio_DataActionPerformed(evt);
            }
        });

        buscarPatrocinio_CNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPatrocinio_CNPJActionPerformed(evt);
            }
        });

        jLabel17.setText("CNPJ:");

        javax.swing.GroupLayout patrocinioBuscarLayout = new javax.swing.GroupLayout(patrocinioBuscar);
        patrocinioBuscar.setLayout(patrocinioBuscarLayout);
        patrocinioBuscarLayout.setHorizontalGroup(
            patrocinioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patrocinioBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patrocinioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patrocinioBuscarLayout.createSequentialGroup()
                        .addGroup(patrocinioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(patrocinioBuscarLayout.createSequentialGroup()
                                .addComponent(buscarPatrocinio_Evento, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 48, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(patrocinioBuscarLayout.createSequentialGroup()
                        .addGroup(patrocinioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patrocinioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buscarPatrocinio_Pat, javax.swing.GroupLayout.Alignment.LEADING, 0, 401, Short.MAX_VALUE)
                                .addComponent(buscarPatrocinio_Edicao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(patrocinioBuscarLayout.createSequentialGroup()
                                .addGroup(patrocinioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(buscarPatrocinio_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(patrocinioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(buscarPatrocinio_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12)
                            .addComponent(buscarPatrocinio_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(patrocinioBuscarLayout.createSequentialGroup()
                .addGroup(patrocinioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patrocinioBuscarLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(buscarPatrocinio_Button))
                    .addGroup(patrocinioBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17))
                    .addGroup(patrocinioBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscarPatrocinio_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        patrocinioBuscarLayout.setVerticalGroup(
            patrocinioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patrocinioBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarPatrocinio_Evento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(5, 5, 5)
                .addComponent(buscarPatrocinio_Edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarPatrocinio_Pat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarPatrocinio_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(patrocinioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(8, 8, 8)
                .addGroup(patrocinioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarPatrocinio_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPatrocinio_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarPatrocinio_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(buscarPatrocinio_Button)
                .addGap(61, 61, 61))
        );

        patrocinioTPane.addTab("Buscar", patrocinioBuscar);

        jLabel23.setText("Evento:");

        deletarPatrocinio_Evento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        deletarPatrocinio_Evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarPatrocinio_EventoActionPerformed(evt);
            }
        });

        jLabel25.setText("CNPJ Patrocinador:");

        jLabel27.setText("Patrocinador:");

        jLabel28.setText("Data:");

        jLabel29.setText("Valor do patrocínio:");

        jLabel30.setText("Saldo do patrocínio:");

        deletarPatrocinio_Saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarPatrocinio_SaldoActionPerformed(evt);
            }
        });

        jButton8.setText("Voltar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        deletarPatrocinio_Button.setText("Deletar");
        deletarPatrocinio_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarPatrocinio_ButtonActionPerformed(evt);
            }
        });

        jLabel35.setText("Ediição:");

        deletarPatrocinio_Edicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        deletarPatrocinio_Edicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarPatrocinio_EdicaoActionPerformed(evt);
            }
        });

        deletarPatrocinio_Pat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        deletarPatrocinio_Pat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarPatrocinio_PatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patrocinioDeletarLayout = new javax.swing.GroupLayout(patrocinioDeletar);
        patrocinioDeletar.setLayout(patrocinioDeletarLayout);
        patrocinioDeletarLayout.setHorizontalGroup(
            patrocinioDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patrocinioDeletarLayout.createSequentialGroup()
                .addGroup(patrocinioDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patrocinioDeletarLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(deletarPatrocinio_Button)
                        .addGap(39, 39, 39)
                        .addComponent(jButton8))
                    .addGroup(patrocinioDeletarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel30))
                    .addGroup(patrocinioDeletarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(patrocinioDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deletarPatrocinio_Saldo, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addGroup(patrocinioDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(deletarPatrocinio_Valor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(deletarPatrocinio_Data, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(deletarPatrocinio_CNPJ, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(patrocinioDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel28)
                                    .addGroup(patrocinioDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(deletarPatrocinio_Evento, 0, 333, Short.MAX_VALUE)
                                        .addComponent(jLabel35)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel27)
                                        .addComponent(deletarPatrocinio_Edicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(deletarPatrocinio_Pat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel29))))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        patrocinioDeletarLayout.setVerticalGroup(
            patrocinioDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patrocinioDeletarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(1, 1, 1)
                .addComponent(deletarPatrocinio_Evento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletarPatrocinio_Edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletarPatrocinio_Pat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel25)
                .addGap(8, 8, 8)
                .addComponent(deletarPatrocinio_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletarPatrocinio_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletarPatrocinio_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletarPatrocinio_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(patrocinioDeletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletarPatrocinio_Button)
                    .addComponent(jButton8))
                .addGap(49, 49, 49))
        );

        patrocinioTPane.addTab("Deletar", patrocinioDeletar);

        jLabel32.setText("Evento");

        editarPatrocinio_Evento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        editarPatrocinio_Evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPatrocinio_EventoActionPerformed(evt);
            }
        });

        jLabel33.setText("Edição:");

        jLabel37.setText("Data do patrocínio:");

        jLabel38.setText("Valor do patrocínio:");

        jButton11.setText("Voltar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        editarPatrocinio_Button.setText("Editar");
        editarPatrocinio_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPatrocinio_ButtonActionPerformed(evt);
            }
        });

        editarPatrocinio_Edicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        editarPatrocinio_Edicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPatrocinio_EdicaoActionPerformed(evt);
            }
        });

        jLabel34.setText("Patrocinador:");

        editarPatrocinio_Pat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        editarPatrocinio_Pat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPatrocinio_PatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editarPatrocinio_ValorLayout = new javax.swing.GroupLayout(editarPatrocinio_Valor);
        editarPatrocinio_Valor.setLayout(editarPatrocinio_ValorLayout);
        editarPatrocinio_ValorLayout.setHorizontalGroup(
            editarPatrocinio_ValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarPatrocinio_ValorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editarPatrocinio_ValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editarPatrocinio_ValorLayout.createSequentialGroup()
                        .addComponent(editarPatrocinio_Evento, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(editarPatrocinio_ValorLayout.createSequentialGroup()
                        .addGroup(editarPatrocinio_ValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(editarPatrocinio_Edicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34)
                            .addComponent(editarPatrocinio_Pat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(editarPatrocinio_ValorLayout.createSequentialGroup()
                                .addGroup(editarPatrocinio_ValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editarPatrocinio_ValorLayout.createSequentialGroup()
                                        .addGroup(editarPatrocinio_ValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel37)
                                            .addComponent(editarPatrocinio_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(61, 61, 61))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarPatrocinio_ValorLayout.createSequentialGroup()
                                        .addComponent(editarPatrocinio_Button)
                                        .addGap(18, 18, 18)))
                                .addGroup(editarPatrocinio_ValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editarPatrocinio_valor)
                                    .addGroup(editarPatrocinio_ValorLayout.createSequentialGroup()
                                        .addGroup(editarPatrocinio_ValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton11)
                                            .addComponent(jLabel38))
                                        .addGap(0, 68, Short.MAX_VALUE)))))
                        .addGap(0, 0, 0))))
        );
        editarPatrocinio_ValorLayout.setVerticalGroup(
            editarPatrocinio_ValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarPatrocinio_ValorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarPatrocinio_Evento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarPatrocinio_Edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarPatrocinio_Pat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(editarPatrocinio_ValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarPatrocinio_ValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarPatrocinio_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarPatrocinio_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(editarPatrocinio_ValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarPatrocinio_Button)
                    .addComponent(jButton11))
                .addGap(64, 64, 64))
        );

        patrocinioTPane.addTab("Editar", editarPatrocinio_Valor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patrocinioTPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patrocinioTPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buscarPatrocinio_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPatrocinio_ButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_buscarPatrocinio_ButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void insertByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertByNameActionPerformed
     
    }//GEN-LAST:event_insertByNameActionPerformed

    private void inserirEv_PatrocinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirEv_PatrocinadorActionPerformed
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        JComboBox jcb = new JComboBox();
        jcb = (JComboBox) evt.getSource();
        try {
            Integer codEv = EventoBD.getCodeByName(jcb.getSelectedItem().toString());
            model = EdicaoBD.getEditions(codEv);
            inserirEd_Patrocinador.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_inserirEv_PatrocinadorActionPerformed

    private void inserirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirButtonActionPerformed

        
        try {
            String valor = new String(inserirValor_Patrocinio.getText());
            String valorPat = NumberFormat.getCurrencyInstance().format(Double.parseDouble(valor));
            if(valorPat.startsWith("£")||(valorPat.startsWith("$"))){
            System.out.println(valorPat);
            valorPat = valorPat.substring(1);
        }
        if(valorPat.contains("R$")) valorPat = valorPat.substring(2);
        if(valorPat.contains(",")){
            valorPat = valorPat.replace(",", "");
        }
        System.out.println(valorPat);
        
            String cnpj = PatrocinadorBD.getCnpjByName(insertByName.getSelectedItem().toString());
            Integer codEv = EventoBD.getCodeByName(inserirEv_Patrocinador.getSelectedItem().toString());
            Integer numEd = Integer.parseInt(inserirEd_Patrocinador.getSelectedItem().toString());
            //String valorPat = valor;
            java.util.Date dataPat = new java.sql.Date(inserirData_Patrocinio.getDate().getTime());
            PatrocinioBD.inserir(cnpj, codEv, numEd,valorPat, dataPat.toString());
            JOptionPane.showMessageDialog(null, "Patrocino cadastrado com sucesso " , "Successo", JOptionPane.INFORMATION_MESSAGE);
            insertByName.setSelectedIndex(0); 
            clearFields();
            loadComboBox();
        } catch (SQLException ex) {
            Logger.getLogger(TelaInscrito.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Valor do Patrocinio incorreto " , "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(TelaInscrito.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_inserirButtonActionPerformed

    private void buscarPatrocinio_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPatrocinio_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarPatrocinio_DataActionPerformed

    private void buscarPatrocinio_CNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPatrocinio_CNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarPatrocinio_CNPJActionPerformed

    private void buscarPatrocinio_EventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPatrocinio_EventoActionPerformed
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        JComboBox jcb = new JComboBox();
        jcb = (JComboBox) evt.getSource();
        if(jcb.getSelectedIndex()==0) return;
        try {
            Integer codEv = EventoBD.getCodeByName(jcb.getSelectedItem().toString());
            model = EdicaoBD.getEditions(codEv);
            clearFields();
            buscarPatrocinio_Pat.setSelectedIndex(0);
            buscarPatrocinio_Edicao.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarPatrocinio_EventoActionPerformed

    private void inserirEd_PatrocinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirEd_PatrocinadorActionPerformed
       
    }//GEN-LAST:event_inserirEd_PatrocinadorActionPerformed

    private void buscarPatrocinio_PatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPatrocinio_PatActionPerformed
        if(buscarPatrocinio_Evento.getSelectedIndex()==0||
                buscarPatrocinio_Edicao.getSelectedIndex()==0) return;
        JComboBox jcb = new JComboBox();
        jcb = (JComboBox) evt.getSource();
        if(jcb.getSelectedIndex()==0) return;
        ArrayList<String> details = new ArrayList<String>();
        try {
            Integer codEv = EventoBD.getCodeByName(buscarPatrocinio_Evento.getSelectedItem().toString());
            Integer numEd = Integer.parseInt(buscarPatrocinio_Edicao.getSelectedItem().toString());
            String cnpjPat = PatrocinadorBD.getCnpjByName(jcb.getSelectedItem().toString());
            details = PatrocinioBD.buscar(cnpjPat, codEv, numEd);
            buscarPatrocinio_CNPJ.setText(details.get(0));
            String valor = new String(details.get(3));
            valor = NumberFormat.getCurrencyInstance().format(Double.parseDouble(valor));
            buscarPatrocinio_Valor.setText(valor);
            buscarPatrocinio_Saldo.setText(details.get(4));
            buscarPatrocinio_Data.setText(details.get(5));
        } catch (SQLException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarPatrocinio_PatActionPerformed

    private void buscarPatrocinio_EdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPatrocinio_EdicaoActionPerformed
        if(buscarPatrocinio_Evento.getSelectedIndex()==0) return;
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        JComboBox jcb = new JComboBox();
        jcb = (JComboBox) evt.getSource();
        if(jcb.getSelectedIndex()==0) return;
        try {
            Integer codEv = EventoBD.getCodeByName(buscarPatrocinio_Evento.getSelectedItem().toString());
            Integer numEd = Integer.parseInt(jcb.getSelectedItem().toString());
            model = PatrocinioBD.buscarPat(codEv, numEd);
            buscarPatrocinio_Pat.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarPatrocinio_EdicaoActionPerformed

    private void editarPatrocinio_EventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPatrocinio_EventoActionPerformed
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        JComboBox jcb = new JComboBox();
        jcb = (JComboBox) evt.getSource();
        if(jcb.getSelectedIndex()==0) return;
        try {
            Integer codEv = EventoBD.getCodeByName(jcb.getSelectedItem().toString());
            model = EdicaoBD.getEditions(codEv);
            clearFields();
            editarPatrocinio_Pat.setSelectedIndex(0);
            editarPatrocinio_Edicao.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarPatrocinio_EventoActionPerformed

    private void editarPatrocinio_EdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPatrocinio_EdicaoActionPerformed
        if(editarPatrocinio_Evento.getSelectedIndex()==0) return;
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        JComboBox jcb = new JComboBox();
        jcb = (JComboBox) evt.getSource();
        if(jcb.getSelectedIndex()==0) return;
        try {
            Integer codEv = EventoBD.getCodeByName(editarPatrocinio_Evento.getSelectedItem().toString());
            Integer numEd = Integer.parseInt(jcb.getSelectedItem().toString());
            model = PatrocinioBD.buscarPat(codEv, numEd);
            editarPatrocinio_Pat.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarPatrocinio_EdicaoActionPerformed

    private void editarPatrocinio_PatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPatrocinio_PatActionPerformed
        if(editarPatrocinio_Evento.getSelectedIndex()==0||
                editarPatrocinio_Edicao.getSelectedIndex()==0) return;
        JComboBox jcb = new JComboBox();
        jcb = (JComboBox) evt.getSource();
        if(jcb.getSelectedIndex()==0) return;
        ArrayList<String> details = new ArrayList<String>();
        try {
            Integer codEv = EventoBD.getCodeByName(editarPatrocinio_Evento.getSelectedItem().toString());
            Integer numEd = Integer.parseInt(editarPatrocinio_Edicao.getSelectedItem().toString());
            String cnpjPat = PatrocinadorBD.getCnpjByName(jcb.getSelectedItem().toString());
            details = PatrocinioBD.buscar(cnpjPat, codEv, numEd);
            String valor = new String(details.get(3));
            valor = NumberFormat.getCurrencyInstance().format(Double.parseDouble(valor));
            editarPatrocinio_valor.setText(valor);
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy"); 
            editarPatrocinio_Data.setDate(dateFormat.parse(details.get(5)));
        } catch (SQLException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        }catch (ParseException ex) {
                Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarPatrocinio_PatActionPerformed

    private void editarPatrocinio_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPatrocinio_ButtonActionPerformed
        if(editarPatrocinio_Evento.getSelectedIndex()==0||
                editarPatrocinio_Edicao.getSelectedIndex()==0||
                editarPatrocinio_Pat.getSelectedIndex()==0) return;
        try {
            String cnpjPat = PatrocinadorBD.getCnpjByName(
                    editarPatrocinio_Pat.getSelectedItem().toString());
            Integer codEv = EventoBD.getCodeByName(editarPatrocinio_Evento.getSelectedItem().toString());
            Integer numEd = Integer.parseInt(editarPatrocinio_Edicao.getSelectedItem().toString());
            java.sql.Date dataPat = new java.sql.Date(editarPatrocinio_Data.getDate().getTime());
            String valorPat = editarPatrocinio_valor.getText();
            if(valorPat.startsWith("£")||(valorPat.startsWith("$"))||(valorPat.startsWith("€"))){
                System.out.println(valorPat);
                valorPat = valorPat.substring(1);
                if(valorPat.contains(",")){
                    valorPat = valorPat.replace(",", "");
                }
            }
            else if(valorPat.contains("R$ ")){
                valorPat = valorPat.substring(3);
                if(valorPat.contains(",")){
                    valorPat = valorPat.replace(",", ".");
                }
            }
            else if(valorPat.contains(",")){
                valorPat = valorPat.replace(",", "");
            }
            System.out.println(valorPat);
            Double valor = Double.parseDouble(valorPat);
            PatrocinioBD.atualizar(cnpjPat, codEv, numEd, valor.toString(), dataPat.toString());
            JOptionPane.showMessageDialog(null, "Atualização Realizada" , "Atualizar", JOptionPane.INFORMATION_MESSAGE);
            clearFields();
            editarPatrocinio_Evento.setSelectedIndex(0);
            editarPatrocinio_Edicao.setSelectedIndex(0);
            editarPatrocinio_Pat.setSelectedIndex(0);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Valor do Patrocinio incorreto " , "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(TelaInscrito.class.getName()).log(Level.SEVERE, null, e);
        }
       
    }//GEN-LAST:event_editarPatrocinio_ButtonActionPerformed

    private void deletarPatrocinio_SaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarPatrocinio_SaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletarPatrocinio_SaldoActionPerformed

    private void deletarPatrocinio_EventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarPatrocinio_EventoActionPerformed
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        JComboBox jcb = new JComboBox();
        jcb = (JComboBox) evt.getSource();
        if(jcb.getSelectedIndex()==0) return;
        try {
            Integer codEv = EventoBD.getCodeByName(jcb.getSelectedItem().toString());
            model = EdicaoBD.getEditions(codEv);
            clearFields();
            deletarPatrocinio_Pat.setSelectedIndex(0);
            deletarPatrocinio_Edicao.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletarPatrocinio_EventoActionPerformed

    private void deletarPatrocinio_EdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarPatrocinio_EdicaoActionPerformed
        if(deletarPatrocinio_Evento.getSelectedIndex()==0) return;
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        JComboBox jcb = new JComboBox();
        jcb = (JComboBox) evt.getSource();
        if(jcb.getSelectedIndex()==0) return;
        try {
            Integer codEv = EventoBD.getCodeByName(deletarPatrocinio_Evento.getSelectedItem().toString());
            Integer numEd = Integer.parseInt(jcb.getSelectedItem().toString());
            model = PatrocinioBD.buscarPat(codEv, numEd);
            deletarPatrocinio_Pat.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletarPatrocinio_EdicaoActionPerformed

    private void deletarPatrocinio_PatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarPatrocinio_PatActionPerformed
         if(deletarPatrocinio_Evento.getSelectedIndex()==0||
                deletarPatrocinio_Edicao.getSelectedIndex()==0) return;
        JComboBox jcb = new JComboBox();
        jcb = (JComboBox) evt.getSource();
        if(jcb.getSelectedIndex()==0) return;
        ArrayList<String> details = new ArrayList<String>();
        try {
            Integer codEv = EventoBD.getCodeByName(deletarPatrocinio_Evento.getSelectedItem().toString());
            Integer numEd = Integer.parseInt(deletarPatrocinio_Edicao.getSelectedItem().toString());
            String cnpjPat = PatrocinadorBD.getCnpjByName(jcb.getSelectedItem().toString());
            details = PatrocinioBD.buscar(cnpjPat, codEv, numEd);
            deletarPatrocinio_CNPJ.setText(details.get(0));
            String valor = new String(details.get(3));
            valor = NumberFormat.getCurrencyInstance().format(Double.parseDouble(valor));
            deletarPatrocinio_Valor.setText(valor);
            deletarPatrocinio_Saldo.setText(details.get(4));
            deletarPatrocinio_Data.setText(details.get(5));
        } catch (SQLException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaPatrocinio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletarPatrocinio_PatActionPerformed

    private void deletarPatrocinio_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarPatrocinio_ButtonActionPerformed
        if(deletarPatrocinio_Evento.getSelectedIndex()==0||
                deletarPatrocinio_Edicao.getSelectedIndex()==0||
                deletarPatrocinio_Pat.getSelectedIndex()==0) return;
        try {
            Integer codEv = EventoBD.getCodeByName(deletarPatrocinio_Evento.getSelectedItem().toString());
            Integer numEd = Integer.parseInt(deletarPatrocinio_Edicao.getSelectedItem().toString());
            String cnpjPat = PatrocinadorBD.getCnpjByName(deletarPatrocinio_Pat.getSelectedItem().toString());
            PatrocinioBD.excluir(cnpjPat, codEv, numEd);
            JOptionPane.showMessageDialog
        (null, "Patrocinio removido" , "Remoção", JOptionPane.INFORMATION_MESSAGE);
        clearFields();
        loadComboBox();
        } catch (SQLException ex) {
            Logger.getLogger(TelaEventos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletarPatrocinio_ButtonActionPerformed
    
    private void loadComboBox(){
        DefaultComboBoxModel modelNames = new DefaultComboBoxModel();
        DefaultComboBoxModel emptyModel = new DefaultComboBoxModel();
        DefaultComboBoxModel emptyModel2 = new DefaultComboBoxModel();
        DefaultComboBoxModel evModel = new DefaultComboBoxModel();
        try {
            modelNames = PatrocinadorBD.getPatName();
            evModel = EventoBD.getEventsName();
            insertByName.setModel(modelNames);
            emptyModel.addElement(" --- ");
            emptyModel.addElement(" Selecione um Evento ");
            emptyModel2.addElement(" --- ");
            emptyModel2.addElement(" Selecione Evento e Edição");
            inserirEv_Patrocinador.setModel(evModel);
            inserirEd_Patrocinador.setModel(emptyModel);
            
            buscarPatrocinio_Evento.setModel(evModel);
            buscarPatrocinio_Edicao.setModel(emptyModel);
            buscarPatrocinio_Pat.setModel(emptyModel2);
            
            editarPatrocinio_Evento.setModel(evModel);
            editarPatrocinio_Edicao.setModel(emptyModel);
            editarPatrocinio_Pat.setModel(emptyModel2);
            
            deletarPatrocinio_Evento.setModel(evModel);
            deletarPatrocinio_Edicao.setModel(emptyModel);
            deletarPatrocinio_Pat.setModel(emptyModel2);
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaPatrocinador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     private void clearFields(){
         
        inserirValor_Patrocinio.setText(" ");
        inserirData_Patrocinio.setDate(null);
        
//        editByName.setSelectedIndex(0);
        editarPatrocinio_valor.setText("");
        editarPatrocinio_Data.setDate(null);

        deletarPatrocinio_CNPJ.setText("");
        deletarPatrocinio_Valor.setText("");
        deletarPatrocinio_Saldo.setText("");
        deletarPatrocinio_Data.setText("");        
        
        buscarPatrocinio_CNPJ.setText("");
        buscarPatrocinio_Valor.setText("");
        buscarPatrocinio_Saldo.setText("");
        buscarPatrocinio_Data.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPatrocinio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPatrocinio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPatrocinio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPatrocinio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPatrocinio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarPatrocinio_Button;
    private javax.swing.JTextField buscarPatrocinio_CNPJ;
    private javax.swing.JTextField buscarPatrocinio_Data;
    private javax.swing.JComboBox buscarPatrocinio_Edicao;
    private javax.swing.JComboBox buscarPatrocinio_Evento;
    private javax.swing.JComboBox buscarPatrocinio_Pat;
    private javax.swing.JTextField buscarPatrocinio_Saldo;
    private javax.swing.JTextField buscarPatrocinio_Valor;
    private javax.swing.JButton deletarPatrocinio_Button;
    private javax.swing.JTextField deletarPatrocinio_CNPJ;
    private javax.swing.JTextField deletarPatrocinio_Data;
    private javax.swing.JComboBox deletarPatrocinio_Edicao;
    private javax.swing.JComboBox deletarPatrocinio_Evento;
    private javax.swing.JComboBox deletarPatrocinio_Pat;
    private javax.swing.JTextField deletarPatrocinio_Saldo;
    private javax.swing.JTextField deletarPatrocinio_Valor;
    private javax.swing.JButton editarPatrocinio_Button;
    private org.jdesktop.swingx.JXDatePicker editarPatrocinio_Data;
    private javax.swing.JComboBox editarPatrocinio_Edicao;
    private javax.swing.JComboBox editarPatrocinio_Evento;
    private javax.swing.JComboBox editarPatrocinio_Pat;
    private javax.swing.JPanel editarPatrocinio_Valor;
    private javax.swing.JTextField editarPatrocinio_valor;
    private javax.swing.JButton inserirButton;
    private org.jdesktop.swingx.JXDatePicker inserirData_Patrocinio;
    private javax.swing.JComboBox inserirEd_Patrocinador;
    private javax.swing.JComboBox inserirEv_Patrocinador;
    private javax.swing.JTextField inserirValor_Patrocinio;
    private javax.swing.JComboBox insertByName;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel patrocinioBuscar;
    private javax.swing.JPanel patrocinioDeletar;
    private javax.swing.JPanel patrocinioInserir;
    protected javax.swing.JTabbedPane patrocinioTPane;
    // End of variables declaration//GEN-END:variables
}
